---
abstract: Makes simple XML tasks a snap!
author:
  - 'Michael Roberts <michael@vivtek.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Snap
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/Vivtek/XML-Snap.git
version: 0.03
